### ISSUE TITLE
error: use of undeclared identifier 'AT_SYMLINK_NOFOLLOW'

### ISSUE THREAD

**Issue by ryandesign** [samtools/htslib#1941]
htslib doesn't build on OS X (macOS) 10.9 and earlier anymore.

htslib 1.21 and earlier did build on such old versions of OS X (macOS), but 1.22.1 fails in this way:

```
ref_cache/log_files.c:84:22: warning: implicit declaration of function 'openat' is invalid in C99 [-Wimplicit-function-declaration]
            log_fd = openat(logfiles->log_dir_fd, name, O_WRONLY | O_CREAT | O_EXCL, 0644);
                     ^
ref_cache/log_files.c:101:9: warning: implicit declaration of function 'unlinkat' is invalid in C99 [-Wimplicit-function-declaration]
        unlinkat(logfiles->log_dir_fd, name, 0);
        ^
ref_cache/log_files.c:218:17: warning: implicit declaration of function 'fstatat' is invalid in C99 [-Wimplicit-function-declaration]
            if (fstatat(logfiles->log_dir_fd,
                ^
ref_cache/log_files.c:219:43: error: use of undeclared identifier 'AT_SYMLINK_NOFOLLOW'
                        ent->d_name, &st, AT_SYMLINK_NOFOLLOW) != 0) {
                                          ^
3 warnings and 1 error generated.
make: *** [ref_cache/log_files.o] Error 1
```

Here is a full build log: https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/311518/steps/install-port/logs/stdio

1.22.1 does build on OS X (macOS) 10.10 and newer.

**Comment by ryandesign** [comment]
> A work-around for systems this old would be to use `./configure --disable-ref-cache`.

Thanks, that works: https://github.com/macports/macports-ports/commit/a132da6870df9c6cca1e0db8fbe82f8207a5674c

> I'll see if I can make that happen automatically where the necessary APIs can't easily be found.

Even better!

> As OS X 10.9 has apparently been unsupported for 9 years now, I'm not inclined to jump through too many hoops for it...

I can understand that perspective, but bear in mind that a user does not always have the choice to upgrade the OS. Apple arbitrarily denies users of old Macs the ability to upgrade their OS so supporting old macOS versions is more important than it would be for e.g. Linux. By continuing to offer new software for old Macs we can keep them from being thrown away unnecessarily. It's why I'm proud MacPorts still works on Mac OS X 10.5 and later.

**Comment by daviesrob** [comment]
If possible, could you try applying the patches in #1945 to see if they fix the problem for you without having to explicitly use `--disable-ref-cache`?
