### ISSUE TITLE
Problem to compile htslib-master

### ISSUE THREAD

**Issue by fabrice-besnard** [samtools/htslib#95]
I am working on a MacOS 10.8.5 and I installed Xtools (+ command lines) v5.1.

When I try to compile htslib-master, I get this error message: 
5 warnings generated. 
gcc -c -g -Wall -Wc++-compat -O2 -Ihtslib vcfnorm.c -o vcfnorm.o 
gcc -c -g -Wall -Wc++-compat -O2 -Ihtslib vcfgtcheck.c -o vcfgtcheck.o 
gcc -g -Wall -Wc++-compat -O2 -o htscmd main.o samview.o vcfview.o bamidx.o bcfidx.o bamshuf.o bam2fq.o tabix.o abreak.o bam2bed.o vcfcheck.o vcfisec.o vcfmerge.o vcfquery.o vcffilter.o vcfnorm.o vcfgtcheck.o -Lhtslib -lhts -lpthread -lz -lm 
Undefined symbols for architecture x86_64: "_bcf_gt_type", referenced from: _main_vcfcheck in vcfcheck.o 
ld: symbol(s) not found for architecture x86_64 
clang: error: linker command failed with exit code 1 (use -v to see invocation) make: **\* [htscmd] Error 1

I want to use htslib along with GATK, following recommandation from teh Broad Institute (http://gatkforums.broadinstitute.org/discussion/2899/howto-install-all-software-packages-required-to-follow-the-gatk-best-practices)

Thank you for your help,
Fabrice
