### ISSUE TITLE
htslib with iRODS support (iRODS 4.1.8)

### ISSUE THREAD

**Issue by stolpeo** [samtools/htslib#366]
I want to compile htslib with iRODS support, but the ./configure command fails stating that he can't find the iRODS API though it is available. I am using the latest checkout of htslib (55ff37c) and iRODS 4.1.8.

```
$ ./configure --with-irods=/vol/local/data/git-clones/irods/iRODS
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for gmtime_r... yes
checking for zlib.h... yes
checking for inflate in -lz... yes
checking for getRodsEnvFileName in -lRodsAPIs... no
configure: error: iRODS development files not found

Support for iRODS URLs requires the libRodsAPI client library and headers.
Configure with --with-irods=DIR (or just --with-irods if $IRODS_HOME has
been exported with a suitable value), where DIR is the base of an iRODS tree
such that the library is present as DIR/lib/core/obj/libRodsAPI.* and headers
are present under DIR/lib/api/include and so on.
```
```
$ ls /vol/local/data/git-clones/irods/iRODS/lib/core/obj/libRodsAPI*
/vol/local/data/git-clones/irods/iRODS/lib/core/obj/libRodsAPIs.a
```

```
$ ls /vol/local/data/git-clones/irods/iRODS/lib/api/include
apiHeaderAll.h       collRepl.h              dataObjRead.h      fileCreate.h          fileUnlink.h               getXmsgTicket.h       rcvXmsg.h         streamRead.h             subStructFileRename.h
apiNumber.h          dataCopy.h              dataObjRename.h    fileGetFsFreeSpace.h  fileWrite.h                ies_client_hints.h    readCollection.h  structFileBundle.h       subStructFileRmdir.h
apiPackTable.h       dataGet.h               dataObjRepl.h      fileGet.h             generalAdmin.h             l3FileGetSingleBuf.h  regColl.h         structFileExtAndReg.h    subStructFileStat.h
apiTable.hpp         dataObjChksum.h         dataObjRsync.h     fileLseek.h           generalRowInsert.h         l3FilePutSingleBuf.h  regDataObj.h      structFileExtract.h      subStructFileTruncate.h
authCheck.h          dataObjClose.h          dataObjTrim.h      fileMkdir.h           generalRowPurge.h          modAccessControl.h    regReplica.h      structFileSync.h         subStructFileUnlink.h
authenticate.h       dataObjCopy.h           dataObjTruncate.h  fileOpendir.h         generalUpdate.h            modAVUMetadata.h      rmColl.h          subStructFileClosedir.h  subStructFileWrite.h
authPluginRequest.h  dataObjCreateAndStat.h  dataObjUnlink.h    fileOpen.h            genQuery.h                 modColl.h             ruleExecDel.h     subStructFileClose.h     syncMountedColl.h
authRequest.h        dataObjCreate.h         dataObjWrite.h     filePut.h             getHierarchyForResc.h      modDataObjMeta.h      ruleExecMod.h     subStructFileCreate.h    ticketAdmin.h
authResponse.h       dataObjGet.h            dataPut.h          fileReaddir.h         getHostForGet.h            objStat.h             ruleExecSubmit.h  subStructFileGet.h       unbunAndRegPhyBunfile.h
bulkDataObjPut.h     dataObjInpOut.h         endTransaction.h   fileRead.h            getHostForPut.h            openCollection.h      sendXmsg.h        subStructFileLseek.h     unregDataObj.h
bulkDataObjReg.h     dataObjLock.h           execCmd.h          fileRename.h          getLimitedPassword.h       oprComplete.h         server_report.h   subStructFileMkdir.h     userAdmin.h
chkNVPathPerm.h      dataObjLseek.h          execMyRule.h       fileRmdir.h           getMiscSvrInfo.h           pamAuthRequest.h      simpleQuery.h     subStructFileOpendir.h   zone_report.h
chkObjPermAndStat.h  dataObjOpenAndStat.h    fileChksum.h       fileStageToCache.h    getRemoteZoneResc.h        phyBundleColl.h       specificQuery.h   subStructFileOpen.h
client_hints.h       dataObjOpen.h           fileChmod.h        fileStat.h            getRescQuota.h             phyPathReg.h          sslEnd.h          subStructFilePut.h
closeCollection.h    dataObjPhymv.h          fileClosedir.h     fileSyncToArch.h      getTempPasswordForOther.h  procStat.h            sslStart.h        subStructFileReaddir.h
collCreate.h         dataObjPut.h            fileClose.h        fileTruncate.h        getTempPassword.h          querySpecColl.h       streamClose.h     subStructFileRead.h
```

I created the iRODS library by compiling the icommand.

Does htslib work with iRODS version 4.1.8 or do I have to choose another one (or do I need to build something different)?

Thanks,
  Oliver

**Comment by jmarshall** [comment]
We mostly build _hfile_irods_ against iRODS 3.3, which works fine.

The code compiles against iRODS 4.1.x, but linking is another story as you've seen.  Last I looked, there was still no clear story in 4.x on what end-user _libfoo.a_ files would be supplied and where, or whether API _.a_ objects would need to be linked with a C++ compiler or what other random dependencies they would bring.

Look also at the end of _config.log_, which will show more details around why _checking for getRodsEnvFileName in -lRodsAPIs_ failed.  It will probably show that you need to ~~compile~~ link _hfile_irods.so_ with a C++ compiler.

**Comment by stolpeo** [comment]
Hi @jmarshall, thanks for your reply. I checked the config.log as you proposed and here is the snippet around the failure when looking for getRodsEnvFileName:

```
...
configure:3903: $? = 0
configure:3912: result: yes
configure:3942: checking for getRodsEnvFileName in -lRodsAPIs
configure:3967: gcc -o conftest -g -O2   -L/vol/local/data/git-clones/irods/iRODS/lib/core/obj conftest.c -lRodsAPIs -lgssapi_krb5 -lpthread  >&5
/vol/local/data/git-clones/irods/iRODS/lib/core/obj/libRodsAPIs.a(getRodsEnv.o): In function `_reloadRodsEnv':
/vol/local/data/git-clones/irods/iRODS/lib/core/src/getRodsEnv.cpp:129: undefined reference to `std::allocator<char>::allocator()'
/vol/local/data/git-clones/irods/iRODS/lib/core/src/getRodsEnv.cpp:129: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char
/vol/local/data/git-clones/irods/iRODS/lib/core/src/getRodsEnv.cpp:129: undefined reference to `std::allocator<char>::allocator()'
...
```

So you were right and the problem comes from C++ code. I checked for the function `getRodsEnvFileName` in the `libRodsAPIs.a` and here is its output. It looks like the function is present but the `gcc` code above is confused by the C++ symbols.

```
$ nm libRodsAPIs.a  | grep getRodsEnvFileName
0000000000000000 T getRodsEnvFileName
nm: libboost_system.a: File format not recognized
nm: libboost_filesystem.a: File format not recognized
nm: libboost_regex.a: File format not recognized
nm: libboost_thread.a: File format not recognized
nm: libboost_chrono.a: File format not recognized
```

What would need to be done to get around this issue? I have some experience with linking a C++ program to a C library but not vice versa.

**Comment by jmarshall** [comment]
For now, start off by trying to hack around the problem :smile:

1. Search _configure_ for `lgssapi`, and add `-lstdc++` to the end of that `LIBS=…` line.

    With luck, this may make configure succeed.  If so…

2. Edit the resulting _config.mk_, and add `-lstdc++` to the end of the `IRODS_LIBS` line.

    With luck, this will make building _hfile_irods.so_ succeed.

If this doesn't get it built, we can hack around it a bit more distastefully.

**Comment by stolpeo** [comment]
I extended the line as you suggested. But it turned out that it can't find other libraries as well, so had to provide them, too:

```
LIBS="-lRodsAPIs -lgssapi_krb5 -lpthread -lstdc++ -lm -L/vol/local/data/git-clones/irods/external/boost_1_58_0z/stage/lib/ -lboost_system -lboost_filesystem -lboost_thread -lboost_regex -lboost_chrono -L/vol/local/data/git-clones/irods/external/jansson-2.7/src/.libs/ -ljansson -L/vol/local/data/git-clones/irods/plugins/network -lssl -L/vol/local/data/git-clones/irods/plugins/auth -lnative -losauth $LIBS"
```

I still can't resolve some missing libraries:

```
configure:3942: checking for getRodsEnvFileName in -lRodsAPIs
configure:3968: gcc -o conftest -g -O2   -L/vol/local/data/git-clones/irods/iRODS/lib/core/obj conftest.c -lRodsAPIs -lgssapi_krb5 -lpthread -lstdc++ -lm -L/vol/local/data/git-clones/irods/external/boost_1_58_0z/stage/lib/ -lboost_system -lboost_filesystem -lboost_thread -lboost_regex -lboost_chrono -L/vol/local/data/git-clones/irods/external/jansson-2.7/src/.libs/ -ljansson -L/vol/local/data/git-clones/irods/plugins/network -lssl -L/vol/local/data/git-clones/irods/plugins/auth -lnative -losauth  >&5
/vol/local/data/git-clones/irods/iRODS/lib/core/obj/libRodsAPIs.a(irods_buffer_encryption.o): In function `irods::buffer_crypt::gen_hash(unsigned char*, int)':
/vol/local/data/git-clones/irods/iRODS/lib/core/src/irods_buffer_encryption.cpp:37: undefined reference to `MD5_Init'
/vol/local/data/git-clones/irods/iRODS/lib/core/src/irods_buffer_encryption.cpp:38: undefined reference to `MD5_Update'
/vol/local/data/git-clones/irods/iRODS/lib/core/src/irods_buffer_encryption.cpp:40: undefined reference to `MD5_Final'
/vol/local/data/git-clones/irods/iRODS/lib/core/obj/libRodsAPIs.a(irods_buffer_encryption.o): In function `irods::buffer_crypt::generate_key(std::vector<unsigned char, std::allocator<unsigned char> >&, int)':
/vol/local/data/git-clones/irods/iRODS/lib/core/src/irods_buffer_encryption.cpp:117: undefined reference to `RAND_bytes'
/vol/local/data/git-clones/irods/iRODS/lib/core/src/irods_buffer_encryption.cpp:120: undefined reference to `ERR_get_error'
/vol/local/data/git-clones/irods/iRODS/lib/core/src/irods_buffer_encryption.cpp:120: undefined reference to `ERR_error_string_n'
/vol/local/data/git-clones/irods/iRODS/lib/core/src/irods_buffer_encryption.cpp:122: undefined reference to `ERR_get_error'
/vol/local/data/git-clones/irods/iRODS/lib/core/obj/libRodsAPIs.a(irods_buffer_encryption.o): In function `irods::buffer_crypt::initialization_vector(std::vector<unsigned char, std::allocator<unsigned char> >&)':
...
/vol/local/data/git-clones/irods/iRODS/lib/core/obj/libRodsAPIs.a(apiHandler.o): In function `irods::error irods::load_plugin<irods::api_entry>(irods::api_entry*&, std::string const&, std::string const&, std::string const&, std::string const&)':
/vol/local/data/git-clones/irods/iRODS/lib/core/include/irods_load_plugin.hpp:189: undefined reference to `dlopen'
/vol/local/data/git-clones/irods/iRODS/lib/core/include/irods_load_plugin.hpp:193: undefined reference to `dlerror'
/vol/local/data/git-clones/irods/iRODS/lib/core/include/irods_load_plugin.hpp:199: undefined reference to `dlerror'
/vol/local/data/git-clones/irods/iRODS/lib/core/include/irods_load_plugin.hpp:204: undefined reference to `dlsym'
/vol/local/data/git-clones/irods/iRODS/lib/core/include/irods_load_plugin.hpp:205: undefined reference to `dlerror'
/vol/local/data/git-clones/irods/iRODS/lib/core/include/irods_load_plugin.hpp:210: undefined reference to `dlclose'
/vol/local/data/git-clones/irods/iRODS/lib/core/include/irods_load_plugin.hpp:220: undefined reference to `dlclose'
/vol/local/data/git-clones/irods/iRODS/lib/core/include/irods_load_plugin.hpp:243: undefined reference to `dlclose'
```

As you can see I already provided libssl and similar libraries that I thought should provide `MD5_init`, but they are undefined. I don't know where iRODS gets those libraries from:

```
$ find /vol/local/data/git-clones/irods -name '*.so' | xargs nm | grep "MD5_Init"
                 U MD5_Init
                 U MD5_Init
                 U MD5_Init
$ find /vol/local/data/git-clones/irods -name '*.a' | xargs nm | grep "MD5_Init"
                 U MD5_Init
                 U MD5_Init
                 U MD5_Init
                 U MD5_Init
                 U MD5_Init
nm: libboost_system.a: File format not recognized
nm: libboost_filesystem.a: File format not recognized
nm: libboost_regex.a: File format not recognized
nm: libboost_thread.a: File format not recognized
nm: libboost_chrono.a: File format not recognized
```

Maybe we can try your unorthodoxly method!

**Comment by jmarshall** [comment]
Adding `-lcrypto -ldl` should provide those remaining missing functions.

**Comment by stolpeo** [comment]
I got it! I had to add a couple of things, because I was getting this error message:

```
configure:3942: checking for getRodsEnvFileName in -lRodsAPIs
configure:3969: gcc -o conftest -g -O2   -L/vol/local/data/git-clones/irods/iRODS/lib/core/obj conftest.c -lRodsAPIs -lgssapi_krb5 -lpthread -lstdc++ -lm -L/vol/local/data/git-clones/irods/external/boost_1_58_0z/s
/vol/local/data/git-clones/irods/iRODS/lib/core/obj/libRodsAPIs.a(apiHandler.o): In function `init_client_api_table':
/vol/local/data/git-clones/irods/iRODS/lib/core/src/apiHandler.cpp:274: undefined reference to `operation_rule_execution_manager_factory'
collect2: error: ld returned 1 exit status
configure:3969: $? = 1
```

Searching for this function brings up https://github.com/irods/irods/issues/3009
So I used `packaging/make_irods_dev_archive.sh` in the irods/iRODS folder to generate the libraries and to link against one of those providing this function. So I added:

```
-L/vol/local/data/git-clones/irods/iRODS/lib/development_libraries -lirods_client_api
```

Full line:

```
LIBS="-lRodsAPIs -lgssapi_krb5 -lpthread -lstdc++ -lm -L/vol/local/data/git-clones/irods/external/boost_1_58_0z/stage/lib/ -lboost_system -lboost_filesystem -lboost_thread -lboost_regex -lboost_chrono -L/vol/local/data/git-clones/irods/external/jansson-2.7/src/.libs/ -ljansson -lssl -lcrypto -ldl -L/vol/local/data/git-clones/irods/iRODS/lib/development_libraries -lirods_client_api $LIBS"
```

And this works! Thanks again.

**Comment by stolpeo** [comment]
For the record: I got samtools compiled with iRODS 4.1.8 support. This is what I did (complete instructions):

```
$ git clone https://github.com/irods/irods
$ cd irods
$ ./packaging/build.sh icommands
$ ./packaging/make_irods_dev_archive.sh
```

```
$ git clone https://github.com/samtools/htslib
$ cd htslib
$ autoconf
$ vi configure

LIBS="-lRodsAPIs -lgssapi_krb5 -lpthread -lstdc++ -lm -L/vol/local/data/git-clones/irods/external/boost_1_58_0z/stage/lib/ -lboost_system -lboost_filesystem -lboost_thread -lboost_regex -lboost_chrono -L/vol/local/data/git-clones/irods/external/jansson-2.7/src/.libs/ -ljansson -lssl -lcrypto -ldl -L/vol/local/data/git-clones/irods/iRODS/lib/development_libraries -lirods_client_api $LIBS"

$ ./configure --with-irods=/vol/local/data/git-clones/irods/iRODS --prefix=/vol/local/data/git-clones/htslib/build
$ vi config.mk

IRODS_LIBS = -lRodsAPIs -lgssapi_krb5 -lpthread -lstdc++ -lm -L/vol/local/data/git-clones/irods/external/boost_1_58_0z/stage/lib/ -lboost_system -lboost_filesystem -lboost_thread -lboost_regex -lboost_chrono -L/vol/local/data/git-clones/irods/external/jansson-2.7/src/.libs/ -ljansson -lssl -lcrypto -ldl -L/vol/local/data/git-clones/irods/iRODS/lib/development_libraries -lirods_client_api

$ make
$ make install
```

```
$ git clone https://github.com/samtools/samtools
$ wget https://github.com/samtools/samtools/files/62424/ax_with_htslib.m4.txt
$ mv ax_with_htslib.m4.txt ax_with_htslib.m4
$ sudo cp ax_with_htslib.m4 /usr/share/aclocal/
$ firefox http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_with_curses.m4
$ vi ax_with_curses.m4 # copy content of txt in here
$ sudo cp ax_with_curses.m4 /usr/share/aclocal/
$ aclocal
$ autoconf
$ ./configure --with-htslib=/vol/local/data/git-clones/htslib --prefix=/vol/local/data/git-clones/samtools/build
$ vi config.mk

LIBS = -L/vol/local/data/git-clones/irods/iRODS/lib/core/obj/ -lRodsAPIs -lgssapi_krb5 -lpthread -lstdc++ -lm -L/vol/local/data/git-clones/irods/external/boost_1_58_0z/stage/lib/ -lboost_system -lboost_filesystem -lboost_thread -lboost_regex -lboost_chrono -L/vol/local/data/git-clones/irods/external/jansson-2.7/src/.libs/ -ljansson -lssl -lcrypto -ldl -L/vol/local/data/git-clones/irods/iRODS/lib/development_libraries -lirods_client_api 

$ make
$ make install
$ export LD_LIBRARY_PATH=/vol/local/data/git-clones/irods/external/jansson-2.7/src/.libs/
$ build/bin/samtools --version
samtools 1.3-23-gcd7e005
Using htslib 1.3-50-g653f45e
Copyright (C) 2016 Genome Research Ltd.
```

There might be an easier way; if so, I would be happy to learn it.

**Comment by jmarshall** [comment]
There is now an easier way: I've now moved the iRODS plugin to a new [samtools/htslib-plugins](https://github.com/samtools/htslib-plugins) repository, hopefully properly supporting 4.x and with detection in the Makefile for building against iRODS 3.x, 4.1.x, or 4.2-to-be.  (Building iRODS within HTSlib rather than as a plugin is no longer supported though.)

If you want to try building this, I'll be interested to hear how it works out for you.

**Comment by holtgrewe** [comment]
@jmarshall How does one actually use the plugin system in htslib? I don't see how I can make htslib-powered apps such as samtools load the irods plugin.

**Comment by jmarshall** [comment]
@holtgrewe: You configure HTSlib with `--enable-plugins` and ensure that your SAMtools was built using that HTSlib, then copy the iRODS plugin (which you've built from the [samtools/htslib-plugins](https://github.com/samtools/htslib-plugins) repo) into the same directory that HTSlib's plugins are in.

That's if you're installing HTSlib via `make install` to some prefix. If you're running in place (i.e., not using `make install` but just running things from the source code directory you've built them in), it's a little more involved — see today's conversation in #895 and some additional upcoming documentation that it seems needs to be written.

You can diagnose any problems by cranking up the verbosity in `htsfile`. Have you installed HTSlib and Samtools or are you running-in-place? What plugin messages do you see from running `htsfile -vv irods:foo.sam`?

**Comment by holtgrewe** [comment]
@jmarshall Exellent. I discovered that there also is `HTS_PATH` that I can set to where my plugins are!

**Comment by jmarshall** [comment]
Re HTS_PATH: like the other environment variables that influence HTSlib and Samtools, it's described in the samtools man page.
