### ISSUE TITLE
htslib/sam.h update breaks compatibility with gcc 4.4.7

### ISSUE THREAD

**Issue by freeseek** [samtools/htslib#857]
With one of the latest updates I cannot compile HTSlib with gcc 4.4.7 anymore. The error is the following:
```
$ gcc -Wall -g -O2 -I.  -c -o hts.o hts.c
In file included from ./cram/cram_samtools.h:61,
                 from cram/cram.h:45,
                 from hts.c:41:
./htslib/sam.h:63: error: redefinition of typedef ‘bam_hdr_t’
htslib/hts.h:209: note: previous declaration of ‘bam_hdr_t’ was here
```
The problem seems to be that in `htslib/hts.h` you have one definition of `bam_hdr_t`:
```
typedef struct bam_hdr_t bam_hdr_t;
```
While in `htslib/sam.h` you have a different definition of `bam_hdr_t`:
```
typedef struct bam_hdr_t {
    int32_t n_targets, ignore_sam_err;
    uint32_t l_text;
    uint32_t *target_len;
    int8_t *cigar_tab;
    char **target_name;
    char *text;
    void *sdict;
    uint32_t ref_count;
} bam_hdr_t;
```
I don't really understand the reason why older version of gcc don't see this as an issue. Is it possible to restructure the code to restore compatibility with gcc 4.4.7?

**Comment by daviesrob** [comment]
We don't generally try to build on anything earlier than gcc 4.6.3, which is why this wasn't spotted earlier.

Could you try building pull request #858 and let us know if it fixes the problem, please?

**Comment by freeseek** [comment]
I have edited the changes from pull request #858 and I can confirm that it now compiles on RHEL6 with gcc 4.4.7 without problems. Thank you! Out of curiosity, what is the git command I should have used to pull the request? I am not too familiar with git yet. :-(

**Comment by jmarshall** [comment]
If you have Rob's fork as a remote, you can just check out the branch. You probably don't (this is the only disadvantage of making PR branches in forks rather than the main samtools/htslib repo), so you can fetch the branch with

    git fetch origin pull/858/head:robfix

(`pull/xyz/head` is a GitHub convention rather than being something baked into Git itself.) See [stackoverflow “check out a pull request on Git to review/test a PR”](https://stackoverflow.com/questions/28103251/check-out-a-pull-request-on-git-to-review-test-a-pr/) which also explains the alternatives.

**Comment by daviesrob** [comment]
Good, as it works for you I'll merge it.
